{
    files: [
      PersistentFile {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        lastModifiedDate: 2024-04-03T14:59:34.528Z,
        filepath: 'C:\\Users\\siddharth\\AppData\\Local\\Temp\\0b7fefa250fda78029872b400',
        newFilename: '0b7fefa250fda78029872b400',
        originalFilename: 'Aadhaar Card_Siddharth Ghosh.pdf',
        mimetype: 'application/pdf',
        hashAlgorithm: false,
        size: 359071,
        _writeStream: [WriteStream],
        hash: null,
        [Symbol(shapeMode)]: false,
        [Symbol(kCapture)]: false
      },
      PersistentFile {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        lastModifiedDate: 2024-04-03T14:59:34.536Z,
        filepath: 'C:\\Users\\siddharth\\AppData\\Local\\Temp\\0b7fefa250fda78029872b401',
        newFilename: '0b7fefa250fda78029872b401',
        originalFilename: 'Anti.pdf',
        mimetype: 'application/pdf',
        hashAlgorithm: false,
        size: 347575,
        _writeStream: [WriteStream],
        hash: null,
        [Symbol(shapeMode)]: false,
        [Symbol(kCapture)]: false
      }
    ]
  }